// export default class FavoritesData {
//   id: number = -1;
//   userId: number = -1;
//   instrumentId: number = -1;
//   dateAdded: number = Date.now();
//
//   constructor(id: number = -1, userId: number = -1, instrumentId: number = -1, dateAdded: number = Date.now()) {
//     this.id = id;
//     this.userId = userId;
//     this.instrumentId = instrumentId;
//     this.dateAdded = dateAdded;
//   }
// }
