// export default class InstrumentsData {
//   id: number = -1;
//   name: string = '';
//   type: string = '';
//   brand: string = '';
//   imageUrl: string = '';
//
//   constructor(id: number = -1, name: string = '', type: string = '', brand: string = '', imageUrl: string = '') {
//     this.id = id;
//     this.name = name;
//     this.type = type;
//     this.brand = brand;
//     this.imageUrl = imageUrl;
//   }
// }
